version: '4'

services:
  jupyterhub: # The primary jupyterhub server
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - ${PWD}/jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - jupyterhub_data:/srv/jupyterhub
    environment:
      - DOCKER_JUPYTER_CONTAINER=jupyterlab_img
      - DOCKER_NOTEBOOK_DIR=/home/spawned/notebooks
      - DOCKER_NETWORK_NAME=jupyterhub_network
      - HUB_IP=jupyterhub
      - LDAP_SERVER=ldap://sam-ldap-prod-01.cssd.pitt.edu
      - LDAP_BIND_DN_TEMPLATE=cn={username},ou=person,ou=people,dc=frank,dc=sam,dc=pitt,dc=edu
    restart: on-failure
    networks:
      - jupyterhub_network

  jupyterlab:
    build: jupyterlab
    image: jupyterlab_img
    container_name: jupyterlab-throaway
    networks:
      - jupyterhub_network

volumes:
  jupyterhub_data:

networks:
  jupyterhub_network:
    name: jupyterhub_network
